### ISSUE TITLE
Error during compilation

### ISSUE THREAD

**Issue by MarkDixonTech** [ag-grid/ag-grid-customise-theme#1]
Module build failed: TypeError: Object.entries is not a function

**Comment by paulrichards19** [comment]
Got the same problem

**Comment by Hauptsatana** [comment]
I had this error too and it is related to Node.js. 
According to [Node.js ES2015 Support](https://node.green/#ES2017-features-Object-static-methods-Object-entriesl) `Object.entries` is fully supported since version 7.5.0 while I had 6.11 installed.

I updated my Node.js up to latest 9.10.1 and it works!
